name: 'Docker Build and Push'

inputs:
  image-name:
    required: true
  dockerfile-path:
    required: true
  registry-token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set lowercase repository owner
      shell: bash
      run: echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
      env:
        OWNER_LC: '${{ github.repository_owner }}'

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.registry-token }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/${{ inputs.image-name }}:${{ github.sha }}
          ghcr.io/${{ env.OWNER_LC }}/${{ inputs.image-name }}:latest