name: CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: maven:3.9.6-eclipse-temurin-21
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build jar
        run: mvn clean package
      - name: Save jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-jar
          path: target/*.jar
          retention-days: 1